/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("furniture3.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object002.geometry}
        material={materials.Wood_01}
        position={[0, 7.06, 6.85]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.Metall_Hrom_01}
        position={[-0.02, 19.25, -4.63]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Object001.geometry}
        material={materials.Pupki_01}
        position={[-5.55, 12.23, 3.09]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Box029.geometry}
        material={materials.Skin_02}
        position={[-0.02, 17.86, 0.93]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Shape001.geometry}
        material={materials.Strochka_02}
        position={[-0.03, 17.86, 0.93]}
        scale={0.03}
      />
    </group>
  );
}

useGLTF.preload("furniture3.gltf");
