/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const Model1 = (props) => {
  const { nodes, materials } = useGLTF("furniture1.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 1, 0]}
        scale={2}
        // rotation={[Math.PI / 6, -Math.PI / 4, 0]}
        castShadow
      >
        <mesh
          geometry={nodes.HUG_ARMCHAIRHUG_Armchair_602_014.geometry}
          material={materials.Base}
        />
      </group>
    </group>
  );
}

useGLTF.preload("furniture1.gltf");

export default Model1